server:
  port: 8080


spring:
  activemq:
#    broker-url: failover:(tcp://192.168.8.226:61616?connectionTimeout=1000,tcp://192.168.8.226:61626?connectionTimeout=1000,tcp://192.168.8.226:61636?connectionTimeout=1000)?timeout=3000
#    broker-url: failover:(tcp://192.168.8.226:61616?connectionTimeout=1000,tcp://192.168.8.226:61626?connectionTimeout=1000,tcp://192.168.8.226:61636?connectionTimeout=1000)?timeout=3000
    broker-url: failover:(tcp://192.168.8.72:61616?connectionTimeout=1000)?timeout=3000
    #用户名
    user: admin
    #密码
    password: 6ZC9Ey1RRhprKgduw7eD
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB

printer:
  topic: test_001